version: '2.1'
services:

  database:
      image: postgres:9.5
      environment:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - POSTGRES_DB
      ports:
        - 5432:5432

  config:
      build: config
      depends_on:
        database:
          condition: service_started

  auth-server:
      build: auth-server
      environment:
        - DEFAULT_USER
        - DEFAULT_PASSWORD
        - AUTH_SECRET

  gateway:
      build: api-gateway
      ports:
        - 8080:80
      depends_on:
        config:
          condition: service_healthy
        registry:
          condition: service_healthy

  registry:
      build: registry
      ports:
        - 8081:80
      depends_on:
        config:
          condition: service_healthy

  product-service:
      build: product-service
      depends_on:
        config:
          condition: service_healthy
        registry:
          condition: service_healthy
      environment:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - POSTGRES_DB

  ordering-service:
      build: ordering-service
      depends_on:
        config:
          condition: service_healthy
        registry:
          condition: service_healthy
      environment:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - POSTGRES_DB

  imgproxy:
      image: darthsim/imgproxy
      environment:
        - IMGPROXY_KEY
        - IMGPROXY_SALT

        - IMGPROXY_BIND=:80
      ports:
        - 9000:80

  image-service:
      build: image-service
      depends_on:
        config:
          condition: service_healthy
        registry:
          condition: service_healthy
      environment:
        - IMGPROXY_KEY
        - IMGPROXY_SALT